### ISSUE TITLE
refresher有明显的卡顿问题，下拉刷新不能自动消失

### ISSUE THREAD

**Issue by Hzzone** [wux-weapp/wux-weapp#54]
![](http://tuchuang-1252747889.cosgz.myqcloud.com/2018-03-24-%E6%9C%AA%E5%91%BD%E5%90%8D-1.gif)

iPhone 6sp 真机

js:
```js
// pages/notifications/notifications.js
import { $wuxRefresher } from '../../dist/components/wux'

Page({
    data: {
        items: [
            {
                user_name: 'Hzzone',
                pic_url: 'http://tuchuang-1252747889.cosgz.myqcloud.com/2018-03-23-01.png',
                time: new Date().toLocaleString(),
                content: '由各种物质组成的巨型球状天体，叫做星球。星球有一定的形状，有自己的运行轨道。由各种物质组成的巨型球状天体，叫做星球。星球有一定的形状，有自己的运行轨道。',
            },
            {

                user_name: 'Hzzone',
                pic_url: 'http://tuchuang-1252747889.cosgz.myqcloud.com/2018-03-23-01.png',
                time: new Date().toLocaleString(),
                content: '由各种物质组成的巨型球状天体，叫做星球。星球有一定的形状，有自己的运行轨道。由各种物质组成的巨型球状天体，叫做星球。星球有一定的形状，有自己的运行轨道。',
            }
        ],
    },
    onLoad() {
        this.refresher = new $wuxRefresher({
            onPulling() {
                console.log('onPulling')
            },
            onRefresh() {
                console.log('onRefresh')
                // 刷新时调用
                setTimeout(() => {
                    const items = this.scope.data.items

                    items.unshift({

                        user_name: 'Hzzone',
                        pic_url: 'http://tuchuang-1252747889.cosgz.myqcloud.com/2018-03-23-01.png',
                        time: new Date().toLocaleString(),
                        content: '由各种物质组成的巨型球状天体，叫做星球。星球有一定的形状，有自己的运行轨道。由各种物质组成的巨型球状天体，叫做星球。星球有一定的形状，有自己的运行轨道。',
                    })

                    this.scope.setData({
                        items: items,
                    })

                    this.events.emit(`scroll.refreshComplete`)
                }, 1000)
            }
        })
        console.log(this.refresher)
    },
    touchstart(e) {
        this.refresher.touchstart(e)
    },
    touchmove(e) {
        this.refresher.touchmove(e)
    },
    touchend(e) {
        this.refresher.touchend(e)
    },
})
```

html:
```
<!--pages/notifications/notifications.wxml-->
<import src="../../dist/components/refresher/refresher.wxml"/>

<view class="container" style="position: absolute; height: 100%; {{ $wux.refresher.style }}" bindtouchstart="touchstart" bindtouchmove="touchmove" bindtouchend="touchend">
	<template is="refresher" data="{{ ...$wux.refresher }}"/>
	<view class="weui-panel weui-panel_access">
        <view class="weui-panel__hd">消息列表</view>
        <view class="weui-panel__bd">
            <navigator wx:for="{{ items }}" wx:key="" url='/pages/notification_detail/notification_detail?user_name={{item.user_name}}&time={{item.time}}&content={{item.content}}&pic={{item.pic_url}}'>
            <view class="weui-media-box weui-media-box_text">
                <view class='user_info'>
                    <image src='{{item.pic_url}}'></image>
                    <view>{{ item.user_name }}</view>
                </view>
                <view class='notification_info'>
                        <view class="time">{{ item.time }}</view>                     
                 <view class="weui-media-box__desc">{{ item.content }}</view>  
                </view>
                
            </view>
            </navigator>
            
        </view>
    </view>
</view>
```

css:
```css
/* pages/notifications/notifications.wxss */
.weui-media-box {
    padding: 10rpx;
}

.weui-media-box image {
    height: 120rpx;
    width: 120rpx;
    padding: 10rpx;
}

.weui-media-box.weui-media-box_text {
    display: flex;
}

.title {
    display: row;
}

.user_info {
    font-size: 30rpx;
    text-align: center;
    display: flex;
    flex-direction: column;
}

.time {
    margin: 10rpx;
    color: black; 
    font-size: 35rpx;
}
.notification_info .weui-media-box__desc{
    margin: 10rpx;
    height: 110rpx;
    -webkit-line-clamp: 3;
}

.weui-panel.weui-panel_access {
    overflow: visible;
}
.container {
    display: block;
}
```
